# This is a basic workflow that is manually triggered
name: BUILD

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  automake:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-latest'
        node:
          # Run tests on minimal version we support
          - '18.10.0'
        NPM_CLIENT:
          - 'pnpm'
    env:
      INSTALL_PACKAGE: true
      NPM_CLIENT: ${{ matrix.NPM_CLIENT }}
    name: Test with ${{ matrix.NPM_CLIENT }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7

      - name: build
        run: make build

      - name: Upload artifact bin
        uses: actions/upload-artifact@v3
        with:
          name: ralph-vscode
          path: |
            ralph-vscode-*.vsix
